# test file

# template:
'''
    '': {
        'name': '',
        'symbol': '',
        'a_num': None,
        'a_mass': None,
        'a_radius': None,
        'electron_config': '', 
        'electronegativity': None,
        'electron_affinity': None,
        'ionization_energies': None,
        'class': '',
        'oxidation_nums': [],
        'melting_temp': None, 
        'boiling_temp': None,
        'd': None,
        'yr': 0 
    },
'''
class Element():
        def __init__(self, name, symbol, a_num, a_mass, a_radius, electron_config, electronegativity, electron_affinity, ionization_energies, e_class, oxidation_nums, melting_temp, boiling_temp, d, yr):
            self.name = name
            self.symbol = symbol
            self.a_num = a_num
            self.a_mass = a_mass
            self.a_radius = a_radius
            self.electron_config = electron_config
            self.electronegativity = electronegativity
            self.electron_affinity = electron_affinity
            self.ionization_energies = ionization_energies
            self.e_class = e_class
            self.oxidation_nums = oxidation_nums
            self.melting_temp = melting_temp
            self.boiling_temp = boiling_temp
            self.d = d
            self.yr = yr  
            
class Table():
    def __init__(self):
        self.table = {
            'H': {
                'name': 'Hydrogen',
                'symbol': 'H',
                'a_num': 1,
                'a_mass': 1.00794, # u
                'a_radius': 30, # pm (picometers)
                'electron_config': '1s1', 
                'electronegativity': 2.2,
                'electron_affinity': 72.8, # kJ/mol
                'ionization_energies': 1312, # kJ/mol
                'class': 'nonmetal',
                'oxidation_nums': [-1,1],
                'melting_temp': 14, # K
                'boiling_temp': 20, # K
                'd': 0.0899, # g/L
                'yr': 1766 # year of discovery
            },
            'He': {
                'name': 'Helium',
                'symbol': 'He',
                'a_num': 2,
                'a_mass': 4.003, # u
                'a_radius': 93, # pm (picometers)
                'electron_config': '1s2', 
                'electronegativity': None,
                'electron_affinity': None, # kJ/mol
                'ionization_energies': 2372, # kJ/mol
                'class': 'noble gas',
                'oxidation_nums': [],
                'melting_temp': 1, # K
                'boiling_temp': 4, # K
                'd': 0.18, # g/L
                'yr': 1895 # year of discovery
            },
            'Li': {
                'name': 'Lithium',
                'symbol': 'Li',
                'a_num': 3,
                'a_mass': 6.941, # u
                'a_radius': 155, # pm (picometers)
                'electron_config': '[He]2s1', 
                'electronegativity': 0.98,
                'electron_affinity': 59.6, # kJ/mol
                'ionization_energies': 513, # kJ/mol
                'class': 'alkali metal',
                'oxidation_nums': [1],
                'melting_temp': 454, # K
                'boiling_temp': 1615, # K
                'd': 530, # g/L
                'yr': 1817 # year of discovery
            },
            'Be': {
                'name': 'Beryllium',
                'symbol': 'Be',
                'a_num': 4,
                'a_mass': 9.012,
                'a_radius': 112,
                'electron_config': '[He]2s2', 
                'electronegativity': 1.57,
                'electron_affinity': None,
                'ionization_energies': None,
                'class': 'alkali earth metal',
                'oxidation_nums': [2],
                'melting_temp': 1561, 
                'boiling_temp': 2744,
                'd': 1850,
                'yr': 1798 
            },
            'B': {
                'name': 'Boron',
                'symbol': 'B',
                'a_num': 5,
                'a_mass': 10.81,
                'a_radius': 98,
                'electron_config': '[He]2s22p1', 
                'electronegativity': 2.04,
                'electron_affinity': 26.7,
                'ionization_energies': 801,
                'class': 'semimetals',
                'oxidation_nums': [3],
                'melting_temp': 2573.15, 
                'boiling_temp': 3923.15,
                'd': 2470,
                'yr': 1808
            },
            'C': {
                'name': 'Carbon',
                'symbol': 'C',
                'a_num': 6,
                'a_mass': 12.01,
                'a_radius': 91,
                'electron_config': '[He]2s22p2', 
                'electronegativity': 2.55,
                'electron_affinity': 153.9,
                'ionization_energies': 1086,
                'class': 'nonmetal',
                'oxidation_nums': [-4, 2, 4],
                'melting_temp': None, 
                'boiling_temp': 3823.15,
                'd': 2260,
                'yr': 0 
            },
            'N': {
                'name': 'Nitrogen',
                'symbol': 'N',
                'a_num': 7,
                'a_mass': 14.01,
                'a_radius': 92,
                'electron_config': '[He]2s22p3', 
                'electronegativity': 3.04,
                'electron_affinity': 7,
                'ionization_energies': 1402,
                'class': 'nonmetal',
                'oxidation_nums': [-3, 2, 3, 4, 5],
                'melting_temp': 63, 
                'boiling_temp': 77,
                'd': 1.25,
                'yr': 1772
            },
            'O': {
                'name': 'Oxygen',
                'symbol': 'O',
                'a_num': 8,
                'a_mass': 16,
                'a_radius': 66,
                'electron_config': '[He]2s22p4', 
                'electronegativity': 3.44,
                'electron_affinity': 141,
                'ionization_energies': 1314,
                'class': 'nonmetal',
                'oxidation_nums': [-2],
                'melting_temp': 54, 
                'boiling_temp': 90,
                'd': 1.43,
                'yr': 1774
            },
            'F': {
                'name': 'Fluorine',
                'symbol': 'F',
                'a_num': 9,
                'a_mass': 19,
                'a_radius': 64,
                'electron_config': '[He]2s22p5', 
                'electronegativity': 3.98,
                'electron_affinity': 328,
                'ionization_energies': 1681,
                'class': 'halogens',
                'oxidation_nums': [-1],
                'melting_temp': 53, 
                'boiling_temp': 85,
                'd': 1.7,
                'yr': 1771
            },
            'Ne': {
                'name': 'Neon',
                'symbol': 'Ne',
                'a_num': 10,
                'a_mass': 20.18,
                'a_radius': 160,
                'electron_config': '[He]2s22p6', 
                'electronegativity': None,
                'electron_affinity': None,
                'ionization_energies': 2081,
                'class': 'noble gas',
                'oxidation_nums': [],
                'melting_temp': 24, 
                'boiling_temp': 27,
                'd': 0.9,
                'yr': 1898 
            },
            'Na': {
                'name': 'Sodium',
                'symbol': 'Na',
                'a_num': 11,
                'a_mass': 22.99,
                'a_radius': 190,
                'electron_config': '[Ne]3s1', 
                'electronegativity': 0.93,
                'electron_affinity': 52.8,
                'ionization_energies': 496,
                'class': 'alkali metals',
                'oxidation_nums': [1],
                'melting_temp': 371, 
                'boiling_temp': 1156,
                'd': 970,
                'yr': 1807
            },
            'Mg': {
                'name': 'Magnesium',
                'symbol': 'Mg',
                'a_num': 12,
                'a_mass': 24.31,
                'a_radius': 160,
                'electron_config': '[Ne]3s2', 
                'electronegativity': 1.31,
                'electron_affinity': None,
                'ionization_energies': 738,
                'class': 'alkali earth metal',
                'oxidation_nums': [2],
                'melting_temp': 923, 
                'boiling_temp': 1363,
                'd': 1740,
                'yr': 1755
            },
            'Al': {
                'name': 'Aluminum',
                'symbol': 'Al',
                'a_num': 13,
                'a_mass': 26.98,
                'a_radius': 143,
                'electron_config': '[Ne]3s23p1', 
                'electronegativity': 1.61,
                'electron_affinity': 42.5,
                'ionization_energies': 578,
                'class': 'p block transition metals',
                'oxidation_nums': [3],
                'melting_temp': 933, 
                'boiling_temp': 2792,
                'd': 2700,
                'yr': 1827
            },
            'Si': {
                'name': 'Silicon',
                'symbol': 'Si',
                'a_num': 14,
                'a_mass': 28.09,
                'a_radius': 132,
                'electron_config': '[Ne]3s23p2', 
                'electronegativity': 1.9,
                'electron_affinity': 133.6,
                'ionization_energies': 786,
                'class': 'semimetal',
                'oxidation_nums': [-4, 2, 4],
                'melting_temp': 1687, 
                'boiling_temp': 3553,
                'd': 2330,
                'yr': 1823 
            },
            'P': {
                'name': 'Phosphorus',
                'symbol': 'P',
                'a_num': 15,
                'a_mass': 30.97,
                'a_radius': 128,
                'electron_config': '[Ne]3s23p3', 
                'electronegativity': 2.19,
                'electron_affinity': 72,
                'ionization_energies': 1012,
                'class': 'nonmetal',
                'oxidation_nums': [-3, 3, 5],
                'melting_temp': 317, 
                'boiling_temp': 553,
                'd': 1820,
                'yr': 0
            },
            'S': {
                'name': 'Sulfur',
                'symbol': 'S',
                'a_num': 16,
                'a_mass': 32.07,
                'a_radius': 104,
                'electron_config': '[Ne]3s23p4', 
                'electronegativity': 2.58,
                'electron_affinity': 200,
                'ionization_energies': 1000,
                'class': 'nonmetal',
                'oxidation_nums': [-2, 4, 6],
                'melting_temp': 388, 
                'boiling_temp': 718,
                'd': 2090,
                'yr': 0 
            },
            'Cl': {
                'name': 'Chlorine',
                'symbol': 'Cl',
                'a_num': 17,
                'a_mass': 35.45,
                'a_radius': 99,
                'electron_config': '[Ne]3s23p5', 
                'electronegativity': 3.16,
                'electron_affinity': 349,
                'ionization_energies': 1251,
                'class': 'halogens',
                'oxidation_nums': [-1, 1, 3, 5, 7],
                'melting_temp': 172, 
                'boiling_temp': 238,
                'd': 3.21,
                'yr': 1774 
            },
            'Ar': {
                'name': 'Argon',
                'symbol': 'Ar',
                'a_num': 18,
                'a_mass': 39.95,
                'a_radius': 191,
                'electron_config': '[Ne]3s23p6', 
                'electronegativity': None,
                'electron_affinity': None,
                'ionization_energies': 1521,
                'class': 'noble gas',
                'oxidation_nums': [],
                'melting_temp': 84, 
                'boiling_temp': 87,
                'd': 1.78,
                'yr': 1894
            },
            'K': {
                'name': 'Potassium',
                'symbol': 'K',
                'a_num': 19,
                'a_mass': 39.1,
                'a_radius': 235,
                'electron_config': '[Ar]4s1', 
                'electronegativity': 0.82,
                'electron_affinity': 48.4,
                'ionization_energies': 419,
                'class': 'alkali metal',
                'oxidation_nums': [1],
                'melting_temp': 336, 
                'boiling_temp': 1033,
                'd': 860,
                'yr': 1807 
            },
            'Ca': {
                'name': 'Calcium',
                'symbol': 'Ca',
                'a_num': 20,
                'a_mass': 40.08,
                'a_radius': 197,
                'electron_config': '[Ar]4s2', 
                'electronegativity': 1,
                'electron_affinity': 2.37,
                'ionization_energies': 590,
                'class': 'alkaline earth metal',
                'oxidation_nums': [2],
                'melting_temp': 1115, 
                'boiling_temp': 1757,
                'd': 1530,
                'yr': 1808
            },
            'Sc': {
                'name': 'Scandium',
                'symbol': 'Sc',
                'a_num': 21,
                'a_mass': 44.96,
                'a_radius': 160,
                'electron_config': '[Ar]3d14s2', 
                'electronegativity': 1.36,
                'electron_affinity': 18.1,
                'ionization_energies': 631,
                'class': 'd block transition metal',
                'oxidation_nums': [3],
                'melting_temp': 1814, 
                'boiling_temp': 3109,
                'd': 2990,
                'yr': 1879 
            },
            'Ti': {
                'name': 'Titanium',
                'symbol': 'Ti',
                'a_num': 22,
                'a_mass': 47.87,
                'a_radius': 146,
                'electron_config': '[Ar]3d24s2', 
                'electronegativity': 1.54,
                'electron_affinity': 7.6,
                'ionization_energies': 658,
                'class': 'd block transition metal',
                'oxidation_nums': [2, 3, 4],
                'melting_temp': 1941, 
                'boiling_temp': 3560,
                'd': 4550,
                'yr': 1791
            },
            'V': {
                'name': 'Vanadium',
                'symbol': 'V',
                'a_num': 23,
                'a_mass': 50.94,
                'a_radius': 134,
                'electron_config': '[Ar]3d34s2', 
                'electronegativity': 1.63,
                'electron_affinity': 50.6,
                'ionization_energies': 651,
                'class': 'd block transition metal',
                'oxidation_nums': [2, 3, 4, 5],
                'melting_temp': 2183, 
                'boiling_temp': 3680,
                'd': 6110,
                'yr': 1830 
            },
            'Cr': {
                'name': 'Chromium',
                'symbol': 'Cr',
                'a_num': 24,
                'a_mass': 52,
                'a_radius': 127,
                'electron_config': '[Ar]3d54s1', 
                'electronegativity': 1.66,
                'electron_affinity': 64.3,
                'ionization_energies': 653,
                'class': 'd block transition metal',
                'oxidation_nums': [2, 3, 6],
                'melting_temp': 2180, 
                'boiling_temp': 2945,
                'd': 7190,
                'yr': 1797 
            },
            'Mn': {
                'name': 'Manganese',
                'symbol': 'Mn',
                'a_num': 25,
                'a_mass': 54.94,
                'a_radius': 126,
                'electron_config': '[Ar]3d54s2', 
                'electronegativity': 1.55,
                'electron_affinity': None,
                'ionization_energies': 717,
                'class': 'd block transition metal',
                'oxidation_nums': [2, 3, 4, 6, 7],
                'melting_temp': 1517, 
                'boiling_temp': 2334,
                'd': 7430,
                'yr': 1774
            },
            'Fe': {
                'name': 'Iron',
                'symbol': 'Fe',
                'a_num': 26,
                'a_mass': 55.85,
                'a_radius': 126,
                'electron_config': '[Ar]3d64s2', 
                'electronegativity': 1.83,
                'electron_affinity': 15.7,
                'ionization_energies': 759,
                'class': 'd block transition metal',
                'oxidation_nums': [2, 3],
                'melting_temp': 1808, 
                'boiling_temp': 3134,
                'd': 7860,
                'yr': 0 
            },
            'Co': {
                'name': 'Cobalt',
                'symbol': 'Co',
                'a_num': 27,
                'a_mass': 58.93,
                'a_radius': 125,
                'electron_config': '[Ar]3d74s2', 
                'electronegativity': 1.88,
                'electron_affinity': 63.7,
                'ionization_energies': 758,
                'class': 'd block transition metal',
                'oxidation_nums': [2, 3],
                'melting_temp': 1768, 
                'boiling_temp': 3200,
                'd': 8800,
                'yr': 1735
            },
            'Ni': {
                'name': 'Nickel',
                'symbol': 'Ni',
                'a_num': 28,
                'a_mass': 58.69,
                'a_radius': 124,
                'electron_config': '[Ar]3d84s2', 
                'electronegativity': 1.91,
                'electron_affinity': 112,
                'ionization_energies': 737,
                'class': 'd block tranisition metal',
                'oxidation_nums': [2, 3],
                'melting_temp': 1728, 
                'boiling_temp': 3186,
                'd': 8900,
                'yr': 1751 
            },
            'Cu': {
                'name': 'Copper',
                'symbol': 'Cu',
                'a_num': 29,
                'a_mass': 63.55,
                'a_radius': 128,
                'electron_config': '[Ar]3d104s1', 
                'electronegativity': 1.9,
                'electron_affinity': 118.4,
                'ionization_energies': 745,
                'class': 'd block transition metal',
                'oxidation_nums': [1, 2],
                'melting_temp': 1357, 
                'boiling_temp': 2840,
                'd': 8960,
                'yr': 0
            },
            'Zn': {
                'name': 'Zinc',
                'symbol': 'Zn',
                'a_num': 30,
                'a_mass': 65.38,
                'a_radius': 133,
                'electron_config': '[Ar]3d104s2', 
                'electronegativity': 1.65,
                'electron_affinity': None,
                'ionization_energies': 906,
                'class': 'd block transition metal',
                'oxidation_nums': [2],
                'melting_temp': 693, 
                'boiling_temp': 1180,
                'd': 7140,
                'yr': 1746
            },
            'Ga': {
                'name': 'Gallium',
                'symbol': 'Ga',
                'a_num': 31,
                'a_mass': 69.72,
                'a_radius': 141,
                'electron_config': '[Ar]3d104s24p1', 
                'electronegativity': 1.81,
                'electron_affinity': 28.9,
                'ionization_energies': 579,
                'class': 'p block transition metals',
                'oxidation_nums': [3],
                'melting_temp': 303, 
                'boiling_temp': 2477,
                'd': 5910,
                'yr': 1875 
            },
            'Ge': {
                'name': 'Germanium',
                'symbol': 'Ge',
                'a_num': 32,
                'a_mass': 72.63,
                'a_radius': 137,
                'electron_config': '[Ar]3d104s24p2', 
                'electronegativity': 2.01,
                'electron_affinity': 119,
                'ionization_energies': 762,
                'class': 'semimetal',
                'oxidation_nums': [2, 4],
                'melting_temp': 1210, 
                'boiling_temp': 3103,
                'd': 5320,
                'yr': 1886 
            },
            'As': {
                'name': 'Arsenic',
                'symbol': 'As',
                'a_num': 33,
                'a_mass': 74.92,
                'a_radius': 139,
                'electron_config': '[Ar]3d104s24p3', 
                'electronegativity': 2.18,
                'electron_affinity': 78,
                'ionization_energies': 947,
                'class': 'semimetal',
                'oxidation_nums': [-3, 3, 5],
                'melting_temp': 1090.15, 
                'boiling_temp': None,
                'd': 5730,
                'yr': 0 
            },
            'Se': {
                'name': 'Selenium',
                'symbol': 'Se',
                'a_num': 34,
                'a_mass': 78.96,
                'a_radius': 140,
                'electron_config': '[Ar]3d104s24p4', 
                'electronegativity': 2.55,
                'electron_affinity': 195,
                'ionization_energies': 941,
                'class': 'nonmetal',
                'oxidation_nums': [-2, 4, 6],
                'melting_temp': 494, 
                'boiling_temp': 958,
                'd': 4810,
                'yr': 1817 
            },
            'Br': {
                'name': 'Bromine',
                'symbol': 'Br',
                'a_num': 35,
                'a_mass': 79.9,
                'a_radius': 114,
                'electron_config': '[Ar]3d104s24p5', 
                'electronegativity': 2.96,
                'electron_affinity': 324.6,
                'ionization_energies': 1140,
                'class': 'halogens',
                'oxidation_nums': [-1, 1, 3, 5],
                'melting_temp': 266, 
                'boiling_temp': 332,
                'd': 3120,
                'yr': 1826 
            },
            'Kr': {
                'name': 'Krypton',
                'symbol': 'Kr',
                'a_num': 36,
                'a_mass': 83.8,
                'a_radius': 200,
                'electron_config': '[Ar]3d104s24p6', 
                'electronegativity': 3,
                'electron_affinity': None,
                'ionization_energies': 1351,
                'class': 'noble gas',
                'oxidation_nums': [],
                'melting_temp': 116, 
                'boiling_temp': 121,
                'd': 3.75,
                'yr': 1897 
            },
            'Rb': {
                'name': 'Rubidium',
                'symbol': 'Rb',
                'a_num': 37,
                'a_mass': 85.47,
                'a_radius': 248,
                'electron_config': '[Kr]5s1', 
                'electronegativity': 0.82,
                'electron_affinity': 46.9,
                'ionization_energies': 403,
                'class': 'alkali metal',
                'oxidation_nums': [1],
                'melting_temp': 312, 
                'boiling_temp': 959,
                'd': 1530,
                'yr': 1861 
            },
            'Sr': {
                'name': 'Strontium',
                'symbol': 'Sr',
                'a_num': 38,
                'a_mass': 87.62,
                'a_radius': 215,
                'electron_config': '[Kr]5s2', 
                'electronegativity': 0.95,
                'electron_affinity': 5.03,
                'ionization_energies': 549,
                'class': '[Kr]5s2',
                'oxidation_nums': [2],
                'melting_temp': 1050, 
                'boiling_temp': 1657,
                'd': 2600,
                'yr': 1790 
            },
            'Y': {
                'name': 'Yttrio',
                'symbol': 'Y',
                'a_num': 39,
                'a_mass': 88.91,
                'a_radius': 179,
                'electron_config': '[Kr]4d15s2', 
                'electronegativity': 1.22,
                'electron_affinity': 29.6,
                'ionization_energies': 616,
                'class': 'd block transition metal',
                'oxidation_nums': [3],
                'melting_temp': 1796, 
                'boiling_temp': 3618,
                'd': 4470,
                'yr': 1794 
            },
            'Zr': {
                'name': 'Zirconium',
                'symbol': 'Zr',
                'a_num': 40,
                'a_mass': 91.22,
                'a_radius': 160,
                'electron_config': '[Kr]4d25s2', 
                'electronegativity': 1.33,
                'electron_affinity': 41.1,
                'ionization_energies': 660,
                'class': 'd block tranistion metal',
                'oxidation_nums': [4],
                'melting_temp': 2125, 
                'boiling_temp': 4682,
                'd': 6490,
                'yr': 1789 
            },
            'Nb': {
                'name': 'Niobium',
                'symbol': 'Nb',
                'a_num': 41,
                'a_mass': 92.91,
                'a_radius': 146,
                'electron_config': '[Kr]4d45s1', 
                'electronegativity': 1.6,
                'electron_affinity': 86.1,
                'ionization_energies': 664,
                'class': 'd block transition metal',
                'oxidation_nums': [3, 5],
                'melting_temp': 2741, 
                'boiling_temp': 5015,
                'd': 8570,
                'yr': 1801 
            },
            'Mo': {
                'name': 'Molybdenum',
                'symbol': 'Mo',
                'a_num': 42,
                'a_mass': 95.95,
                'a_radius': 139,
                'electron_config': '[Kr]4d55s1', 
                'electronegativity': 2.16,
                'electron_affinity': 71.9,
                'ionization_energies': 685,
                'class': 'd block transition metal',
                'oxidation_nums': [1, 2, 3, 4, 5, 6],
                'melting_temp': 2829, 
                'boiling_temp': 4912,
                'd': 10200,
                'yr': 1778 
            },
            'Tc': {
                'name': 'Technetium',
                'symbol': 'Tc',
                'a_num': 43,
                'a_mass': 98.91,
                'a_radius': 136,
                'electron_config': '[Kr]4d55s2', 
                'electronegativity': 1.9,
                'electron_affinity': 53,
                'ionization_energies': 702,
                'class': 'd block transition metal',
                'oxidation_nums': [4, 5, 6, 7],
                'melting_temp': 2430, 
                'boiling_temp': 4538,
                'd': 11500,
                'yr': 1937 
            },
            'Ru': {
                'name': 'Ruthenium',
                'symbol': 'Ru',
                'a_num': 44,
                'a_mass': 101.1,
                'a_radius': 133,
                'electron_config': '[Kr]4d75s1', 
                'electronegativity': 2.2,
                'electron_affinity': 101.3,
                'ionization_energies': 711,
                'class': 'd block transition metal',
                'oxidation_nums': [2, 3, 4, 5, 6, 7],
                'melting_temp': 2607, 
                'boiling_temp': 4423,
                'd': 12500,
                'yr': 1844 
            },
            'Rh': {
                'name': 'Rhodium',
                'symbol': 'Rh',
                'a_num': 45,
                'a_mass': 102.9,
                'a_radius': 134,
                'electron_config': '[Kr]4d85s1', 
                'electronegativity': 2.28,
                'electron_affinity': 109.7,
                'ionization_energies': 720,
                'class': 'd block transition metal',
                'oxidation_nums': [3],
                'melting_temp': 2239, 
                'boiling_temp': 3968,
                'd': 12400,
                'yr': 1803 
            },
        }
        
        #print(self.table.elem)
        
        for i in self.table:
            self.table[i] = Element(self.table[i]["name"],
                                   self.table[i]["symbol"],
                                   self.table[i]["a_num"],
                                   self.table[i]["a_mass"],
                                   self.table[i]["a_radius"],
                                   self.table[i]["electron_config"],
                                   self.table[i]["electronegativity"],
                                   self.table[i]["electron_affinity"],
                                   self.table[i]["ionization_energies"],
                                   self.table[i]["class"],
                                   self.table[i]["oxidation_nums"],
                                   self.table[i]["melting_temp"],
                                   self.table[i]["boiling_temp"],
                                   self.table[i]["d"],
                                   self.table[i]["yr"])
    
    def elem(self, ind):
        return self.table[ind]
               
t = Table()

t.elem("O").yr = 10 # NON deve accadere

print(t.elem("O").yr)